/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects and is committed here so
// TypeScript can compile before the first local dev run.
